#!/bin/sh
staged_files=$(git diff --staged --name-only | grep -E '\.(cpp|h)$')

if [ -n "$staged_files" ]; then
    echo "Format changed files..."
    echo "$staged_files" | tee /dev/tty | xargs clang-format -i
fi


git add -u
